### ISSUE TITLE
最近使用本项目做了下helm调用验证，代码做了部分修改，望解答疑惑

### ISSUE THREAD

**Issue by HanshengLi1993** [yxxhero/python-helm#6]
环境：
    python：3.6
    tiller：2.11.0
    k8s：1.13.3
问题：
    1./python-helm/pyhelm/chart/create.py line:32 "mode=0755" => "mode=0o755" or "mode=0x755"
    mode的值是16进制的还是8进制的？
    2./python-helm/pyhelm/tiller.py line:199/237 由于注释掉该行，在使用
    "tiller_ins.install_release(chart.get_helm_chart(), dry_run=False, namespace='default')"
    时，values的默认值为None，直接传给InstallReleaseRequest/UpdateReleaseRequest方法，导致参数解析错误。

**Comment by yxxhero** [comment]
好的  等我今天看看  最近在忙别的  过一阵会继续完善

**Comment by yxxhero** [comment]
/python-helm/pyhelm/chart/create.py 这部分是网友贡献的 不是我自己的写的  
1. mode=0o755 这个可以从python官方文档看到
2. 我看了代码，确实存在此问题，你可以取消注释测试一下， 有问题再找我 我来修复您说的问题

**Comment by HanshengLi1993** [comment]
感谢您的回复，我测试后发现需要将注释取消并加上
import yaml
from hapi.chart.config_pb2 import Config
两句引用，即可正常使用

**Comment by yxxhero** [comment]
ok  bugfix

**Comment by yxxhero** [comment]
可以一起提pr  或者你有啥需求也可以和我说
